config/routes.rb
Shirtbase::Application.routes.draw do

  get "home/index"

  resources :shirts do
    resources :images, :only => [:create]
    resource :favorite, :only => [:create, :destroy]
  end
  
  resources :users, :only => :index do
    resources :shirts
  end
  
  resources :mails, :only => [:create]
  
  resources :tags

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout

  root :to => "Home#index"
  
  match "/imprint" => "StaticPages#imprint", :as => 'imprint'
  match "/data-retention" => "StaticPages#data_retention", :as => 'data_retention'
  

end

app/models/shirt.rb
class Shirt < ActiveRecord::Base
  has_many :shirt_images
  has_many :shirt_ownerships
  has_many :owners, :through => :shirt_ownerships, :source => :user
  belongs_to :user
  has_many :favorites
  has_many :users_who_faved, :through => :favorites, :source => :user

  after_initialize :create_tweet

  acts_as_taggable
  
  validates :name, :presence => true
  validate :validate_len_of_tweet

  has_friendly_id :name, :use_slug => true  

  attr_accessible :name, :want_tweet, :tweet, :description

  include ActionView::Helpers::TextHelper
    
  # def initialize(*params)
  #   create_tweet
  #   super
  # end
  
  attr_accessor :want_tweet
  attr_accessor :tweet  
  
  def send_tweet(url)
    return if @want_tweet.blank? || @want_tweet != '1'
    return if @tweet.blank?
    logger.debug("About to send a tweet, woot! ")
    Twitter.configure do |config|
      config.oauth_token = user.access_token
      config.oauth_token_secret = user.access_token_secret
    end
    tweet_text = @tweet.gsub(/\[SHIRT\]/, truncate(name, :length => 115 - short_tweet.length)).gsub(/\[LINK\]/, url)
    result = Twitter.update("#{tweet_text}")
    logger.debug(result.inspect)
  rescue => e
    logger.error(e)
  end
  
private
  def create_tweet
    @tweet ||= "just added [SHIRT] to @outtacotton [LINK]"
  end
  
  def short_tweet
    @short_tweet ||= @tweet.gsub(/\[SHIRT\]/, '').gsub(/\[LINK\]/, '') if @tweet
  end
  
  def validate_len_of_tweet
    return if short_tweet.nil?
    if (115-short_tweet.length) < 10
      errors.add(:tweet, 'Sorry, your tweet text is too long to make sense')
    end
  end
  
end

app/controllers/shirts_controller.rb
class ShirtsController < ApplicationController
  
  before_filter :load_scope
  
  before_filter :ensure_owner, :only => [:edit, :update, :destroy]
  
  before_filter :login_required!, :only => [:create, :update, :new, :edit, :destroy]
  
  # GET /shirts
  # GET /shirts.json
  def index
    @shirts = @scope.order("created_at DESC").page(params[:page])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shirts }
      format.atom { @shirts = @shirts.limit(20) }
    end
  end

  # GET /shirts/1
  # GET /shirts/1.json
  def show
    @shirt = @scope.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shirt }
    end
  end

  # GET /shirts/new
  # GET /shirts/new.json
  def new
    if @user.nil?
      redirect_to new_user_shirt_path(current_user) and return
    end
    @shirt = Shirt.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shirt }
    end
  end

  # GET /shirts/1/edit
  def edit
    @shirt = @scope.find(params[:id])
  end

  # POST /shirts
  # POST /shirts.json
  def create
    @shirt = Shirt.new(params[:shirt])
    if params[:transloadit]
      image = ShirtImage.from_transloadit(JSON.parse(params[:transloadit]))
      @shirt.shirt_images << image if image
    end
    @shirt.user = current_user
    @shirt.owners << current_user
    respond_to do |format|
      if @shirt.save
        @shirt.send_tweet(shirt_url(@shirt))
        
        format.html { redirect_to user_shirts_path(current_user), notice: 'Shirt was successfully created.' }
        format.json { render json: @shirt, status: :created, location: @shirt }
      else
        format.html { render action: "new" }
        format.json { render json: @shirt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shirts/1
  # PUT /shirts/1.json
  def update
    @shirt = @scope.find(params[:id])
    if params[:transloadit]
      image = ShirtImage.from_transloadit(JSON.parse(params[:transloadit]))
      @shirt.shirt_images << image if image
    end
    respond_to do |format|
      if @shirt.update_attributes(params[:shirt])
        format.html { redirect_to user_shirts_path(current_user), notice: 'Shirt was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @shirt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shirts/1
  # DELETE /shirts/1.json
  def destroy
    @shirt = @scope.find(params[:id])
    @shirt.destroy

    respond_to do |format|
      format.html { redirect_to shirts_url }
      format.json { head :ok }
    end
  end

  def load_scope
    if params[:user_id]
      @user = User.find_by_nickname(params[:user_id])
      @scope = @user.shirts
      @feed_url = user_shirts_url(@user, :format => :atom)
    else
      @scope = Shirt
    end    
  end
  
  def ensure_owner
    @user && @user == current_user
  end
  
end

app/helpers/shirts_helper.rb
module ShirtsHelper
end

app/views/shirts/_feed_item.atom.haml
- if shirt.shirt_images.first
  = image_tag(shirt.shirt_images.first.large_url)
=simple_format(shirt.description)

app/views/shirts/_form.html.erb
<%= form_for(@shirt, :html => {:class => 'shirt-upload'}) do |f| %>
  <% if @shirt.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@shirt.errors.count, "error") %> prohibited this shirt from being saved:</h4>

      <ul>
      <% @shirt.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, :class => 'large', :length => 40, :placeholder => 'The one with the unicorns and the rainbow' %>
  </div>
  <div class="field">
    <%= label_tag :image, "Photo" %>
    <%= file_field_tag :image %>
    <%= hidden_field_tag :params, { auth: {key: ENV['TRANSLOADIT_AUTH_KEY']}, template_id: "42cb74a7389c45da9e3739d63ff06cc7"}.to_json %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, :placeholder => 'Please tell us the story of this shirt', :rows => 5 %>
  </div>
  <div class="field">
    <%= f.label :url, "Source URL" %>
    <%= f.text_field :url, :placeholder => 'http://example.com' %>
  </div>
  <div class="field">
    <%= f.label :tag_list, "Tags" %>
    <%= f.text_field :tag_list, :placeholder => 'comma, separated, tags' %>
  </div>
  <%- if @shirt.new_record? -%>
    <div class="field">
      <label>Shall we tweet this for you?</label>
    </div>
    <div class="field checkbox">    
      <%= f.check_box :want_tweet %>
      <%= f.label :want_tweet, "Yes, please" %>
    </div>
    <div class="field">
      <%= f.label :tweet, "This would be the text" %>
      <%= f.text_area :tweet, :rows => 2 %>
    </div>
  <%- end -%>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<div class="explanation">
  <p>Please give your T-Shirt a comprehensive and concise name</p>
  <p>It's okay to upload photos in portrait or landscape, but most of the time, portrait gives better results</p>
  <p>
    Please don't upload unprocessed 12 Megapixel jpegs directly from your Digicam. We pay for bandwith and although we shrink down
    the images before storing them, we have to pay for the data transfer of the fat ass 12 MP image to the image upload service. Which hurts.
  </p>
  <p>
    If you want to give your t-shirt a description, try to tell an interesting story, for example, where you bought (or got) the shirt, 
    how you found it or if there's any episode that you connect with wearing this t-shirt.
  </p>
  <p>If you bought the shirt online, feel free to add a source url to the product page of the online shop if possible. Somewhere 
    in the future this might enable us to start affiliate programs, which would be awesome to pay the server bills. In the meantime,
    it allows other people to shop for the t-shirt.
  </p>
  <p>
    We will hopefully be able to support you a bit more on the tagging front. So far, please separate tags with commas, and try to not 
    tag like a dizee rascal. Colors make great tags, vendors (tshirtstore, threadless, cafepress, rumpfkluft etc.) make great tags and
    genres (funny, remix, art, type) make great tags. Your mom doesn't make a great tag.    
  </p>
  <p>
    <i>
      If you are taking your photos on an iPhone (and file upload with the browser is out of question), you could send your picture to your own private
      straightouttacotton.com email address. We'll use the subject as the shirt name and any text you add to the mail as the description. Currently that 
      means that you can't add an URL to the Shirt by sending a mail.
    </i>
  </p>
  <p>In your case, that would be <b><%= mail_to "#{current_user.mailbox}@straightouttacotton.com" %></b></p>
</div>

app/views/shirts/_mosaic.html.haml
.shirt-mosaic
  - @shirts.each_slice(4) do |slice|
    .mosaic-row
      - slice.each_with_index do |shirt, counter|
        .mosaic-shirt{:class => (counter % 4 == 3) && 'last' }
          %h3= link_to shirt.name, shirt
          - unless shirt.shirt_images.empty?
            = link_to image_tag(shirt.shirt_images.first.large_url), shirt
          .meta-author
            #{time_ago_in_words shirt.created_at} ago by
            - if shirt.user
              = user_link(shirt.user)
            - else
              anonymous
          .meta-tags
            = raw shirt.tag_list.map{|tag| link_to h(tag), tag_path(tag)}.join(", ")
          .meta-favs
            #{pluralize(shirt.favorites.size, "Fav", "Faves")}

app/views/shirts/edit.html.erb
<h1>Editing shirt</h1>

<%= render 'form' %>

<%= link_to 'Show', @shirt %> |
<%= link_to 'Back', shirts_path %>

app/views/shirts/index.html.haml
- if @user
  %h2 #{user_link(@user)}'s Shirts
  - @page_title = "#{@user.nickname}'s Shirts"
- elsif @tag
  %h2 Shirts tagged with #{@tag}
  - @page_title = "Shirts tagged with #{@tag}"
- else
  %h2 Latest shirts from the shirties
  - @page_title = "Latest shirts from the shirties"

= render 'shirts/mosaic'
= paginate @shirts

app/views/shirts/new.html.erb
<h2>New shirt</h2>

<%= render 'form' %>

app/views/shirts/show.html.haml
- @page_title = "#{@shirt.name}"
%article.shirt
  %h2= link_to @shirt.name, @shirt
  .image
    - if @shirt.shirt_images.first
      = link_to image_tag(@shirt.shirt_images.first.large_url), @shirt
  .meta
    .description
      = simple_format(@shirt.description)

    %p
      posted #{time_ago_in_words @shirt.created_at} ago by
      - if @shirt.user
        = user_link(@shirt.user)
      - else
        anonymous
      - unless @shirt.tag_list.empty?
        &mdash;
        tagged with
        = raw @shirt.tag_list.map{|tag| link_to h(tag), tag_path(tag)}.join(", ")
    %p
      - if @shirt.url
        = link_to @shirt.url, @shirt.url
    - if @shirt.user && @shirt.user == current_user
      %p
        = link_to "[EDIT]", edit_shirt_path(@shirt)
        
    %p
      This shirt has been faved #{pluralize(@shirt.favorites.size, "Time", "Times")}
      - if @shirt.favorites.size > 0 
        by
      = @shirt.users_who_faved.map{ |user| link_to user.nickname, user_shirts_path(user) }.join(", ").html_safe
    - if signed_in?
      %p
        - unless @shirt.users_who_faved.include?(current_user)
          = button_to "Fav", shirt_favorite_path(@shirt), :method => :post
        - else
          = button_to "Unfav", shirt_favorite_path(@shirt), :method => :delete
        
  #disqus_thread
    - if Rails.env.development?
      :javascript
        var disqus_developer = true;
    
    :javascript
      var disqus_shortname = 'straightouttacotton'; // required: replace example with your forum shortname
      var disqus_identifier = '#{@shirt.id}';
      var disqus_title = '#{@shirt.name}';

      (function() {
          var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
          dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
          (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
      })();
    <a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
      
  
        