config/routes.rb
Shirtbase::Application.routes.draw do

  get "home/index"

  resources :shirts do
    resources :images, :only => [:create]
    resource :favorite, :only => [:create, :destroy]
  end
  
  resources :users, :only => :index do
    resources :shirts
  end
  
  resources :mails, :only => [:create]
  
  resources :tags

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout

  root :to => "Home#index"
  
  match "/imprint" => "StaticPages#imprint", :as => 'imprint'
  match "/data-retention" => "StaticPages#data_retention", :as => 'data_retention'
  

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :shirt
  belongs_to :user
end

app/models/shirt.rb
class Shirt < ActiveRecord::Base
  has_many :shirt_images
  has_many :shirt_ownerships
  has_many :owners, :through => :shirt_ownerships, :source => :user
  belongs_to :user
  has_many :favorites
  has_many :users_who_faved, :through => :favorites, :source => :user

  after_initialize :create_tweet

  acts_as_taggable
  
  validates :name, :presence => true
  validate :validate_len_of_tweet

  has_friendly_id :name, :use_slug => true  

  attr_accessible :name, :want_tweet, :tweet, :description

  include ActionView::Helpers::TextHelper
    
  # def initialize(*params)
  #   create_tweet
  #   super
  # end
  
  attr_accessor :want_tweet
  attr_accessor :tweet  
  
  def send_tweet(url)
    return if @want_tweet.blank? || @want_tweet != '1'
    return if @tweet.blank?
    logger.debug("About to send a tweet, woot! ")
    Twitter.configure do |config|
      config.oauth_token = user.access_token
      config.oauth_token_secret = user.access_token_secret
    end
    tweet_text = @tweet.gsub(/\[SHIRT\]/, truncate(name, :length => 115 - short_tweet.length)).gsub(/\[LINK\]/, url)
    result = Twitter.update("#{tweet_text}")
    logger.debug(result.inspect)
  rescue => e
    logger.error(e)
  end
  
private
  def create_tweet
    @tweet ||= "just added [SHIRT] to @outtacotton [LINK]"
  end
  
  def short_tweet
    @short_tweet ||= @tweet.gsub(/\[SHIRT\]/, '').gsub(/\[LINK\]/, '') if @tweet
  end
  
  def validate_len_of_tweet
    return if short_tweet.nil?
    if (115-short_tweet.length) < 10
      errors.add(:tweet, 'Sorry, your tweet text is too long to make sense')
    end
  end
  
end

app/models/shirt_image.rb
class ShirtImage < ActiveRecord::Base
  belongs_to :shirt
  attr_accessible :thumbnail_url, :medium_url, :large_url
  
  def self.from_transloadit(params)
    return nil if params['results'].nil? || params['results'].empty?
    ShirtImage.new(
      thumbnail_url: params['results']['thumbnail'].first['url'],
      medium_url: params['results']['medium'].first['url'],
      large_url: params['results']['large'].first['url']
    )
  end
  
end

app/models/shirt_ownership.rb
class ShirtOwnership < ActiveRecord::Base
  belongs_to :user
  belongs_to :shirt
end

app/models/token.rb
class Token
  VOWELS = %w[a e i o u]
  CONSONANTS = ("a".."z").to_a - VOWELS
  NUMBERS = (0..9).to_a

  def self.readable(size = 12)
    String.new.tap do |s|
      half = size / 2

      1.upto(size) do |i|
        if i == half
          char = NUMBERS.sample.to_s
        elsif i.odd?
          char = CONSONANTS.sample
        else
          char = VOWELS.sample
        end

        s << (NUMBERS.sample.even? ? char.upcase : char)
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :shirt_ownerships
  has_many :shirts, :through => :shirt_ownerships, :source => :shirt
  
  has_many :created_shirts, :foreign_key => :user_id, :class_name => "Shirt"
  
  before_create :ensure_mailbox
  
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["user_info"]["name"]
      user.nickname = auth["user_info"]["nickname"]
      user.access_token = auth["credentials"]["token"]
      user.access_token_secret = auth["credentials"]["secret"]
    end
  end
  
  def self.by_oauth(auth)
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"])
    if user      
      user.update_attributes(:access_token => auth["credentials"]["token"], :access_token_secret => auth["credentials"]["secret"])
    else 
      user = User.create_with_omniauth(auth)
    end
    user
  end
  
  def to_param
    nickname
  end
  
private

  def ensure_mailbox
    return if mailbox.present?
    token = ""
    begin 
      token = Token.readable(8)
    end while User.find_by_mailbox(token)
    self.mailbox = token
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @shirts = Shirt.order("created_at DESC").limit(8)
  end

end

app/controllers/mails_controller.rb
require 'mail'
class MailsController < ApplicationController
  skip_before_filter :verify_authenticity_token
    
  # this controller action is pretty insecure, but it tries to validate as much as possible.
  def create
    transloadit = Transloadit.new(
      :key    => ENV['TRANSLOADIT_AUTH_KEY'],
      :secret => ENV['TRANSLOADIT_AUTH_SECRET']
    )

    to = Mail::Address.new(params[:to])
    subject = params[:subject]
    text = params[:text] || params[:html] # will be used as description
    
    if (user = User.find_by_mailbox(to.local))
      attachment_count = params[:"attachments"].to_i
      if attachment_count > 0
        attachment_info = JSON.parse(params[:"attachment-info"])
        attachment_keys = attachment_info.select { |k,v| v['type'].match(/^image\//)}.map(&:first)
        attachments = []
        attachment_keys.each do |k|
          attachments.push(params[k])
        end
        unless attachments.empty?
          shirt = user.created_shirts.build(
            :name => subject,
            :description => text
          )
          shirt.owners << shirt.user
          if shirt.save
            transloadit.assembly(
              :template_id => "42cb74a7389c45da9e3739d63ff06cc7",
              :fields => { :shirt_id => shirt.to_param },
              :notify_url => shirt_images_url(shirt)
            ).submit!(*attachments)
          end
        end
      end
    end
    
    
    
    render :text => 'Thank you, Mr. Sendgrid'
  end
  
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  
  def show
    @tag = params[:id]
    @shirts = Shirt.tagged_with(params[:id]).order("created_at DESC").page(params[:page])
    @feed_url = tag_url(:id => @tag, :format => :atom)
    render "shirts/index"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/mails_helper.rb
module MailsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shirts_helper.rb
module ShirtsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_link(user)
    link_to user.nickname, user_shirts_path(user)
  end
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title %> - straight outta cotton</title>
  <%= stylesheet_link_tag    "application" %>
  <%= stylesheet_link_tag    "smallscreen", :media => "only screen and (max-width: 1023px)" %>
  <%= stylesheet_link_tag    "mobile", :media => "handheld, only screen and (max-width: 767px)" %>
  
  
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "http://assets.transloadit.com/js/jquery.transloadit2.js" %>
  <%= csrf_meta_tags %>
  <link rel="alternate" type="application/atom+xml" href="<%= @feed_url || shirts_url(:format => :atom) %>">
  <meta name="description" content="A Collection of clever tees from people who like clever tees">
  <meta name="keywords" content="tshirts, t-shirts, shirts, tees, collection, people">
  <meta name = "viewport" content = "width=device-width, initial-scale=1"> 
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-24444888-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>  
</head>
<body class="<%= controller.controller_name %>">
  <section class="header">
    <div class="header-content">
      <h1><a href="/">straight<br/>outta<br/>cotton</a></h1>
      <section class="user-nav">
        <% if signed_in? %>
          signed in as <%= user_link(current_user) %>
          /
          <%= link_to "sign out", signout_path %>
          /
          <%= link_to "add your tee", new_user_shirt_path(current_user) %>
        <% else %>
          <%= link_to "sign in with twitter", "/auth/twitter" %>
        <% end %>
        <navigation class="feed-links">
          <%= link_to "ATOM", @feed_url || shirts_url(:format => :atom), :class => 'atom-link' %>
        </navigation>
      </section>
    </div>
  </section>
  <div class="container">
    <section class="main">
      <div class="content">
      <%= yield %>
      </div>
    </section>
  
  </div>
  <section class="footer">
    <div class="footer-text">
      <p>The T-Shirt Database</p>
      <p>&copy; Jan Krutisch</p>
      <p>
        <%= link_to "Imprint/Impressum", imprint_path %>
        | <%= link_to "Datenschutz", data_retention_path %>
      </p>
    </div>
  </section>
</body>
</html>